name: todolist
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.1.3
  sqflite: ^1.3.0+1
  path_provider: ^1.6.10
  pedantic: ^1.9.0
  flutter_neumorphic:
    git:
      url: git://github.com/Idean/Flutter-Neumorphic.git
  font_awesome_flutter: ">=8.8.1"
  intl: ^0.16.1
  expandable: ^4.1.4
  flare_flutter: ^2.0.3
  easy_localization: ^2.3.2
  shared_preferences: ">=0.5.7+3 <2.0.0"
  animated_background: ^1.0.5
  package_info: ">=0.4.1 <2.0.0"
  url_launcher: ^5.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: false
  adaptive_icon_background: "#dedede" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/icon/icon_foreground.png" # only available for Android 8.0 devices and above
#flutter pub run flutter_launcher_icons:main

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animation/
    - assets/locales/
    - assets/icon/
